### PR TITLE
Made the following additions:

### PR DESCRIPTION
**Pull request by gigapod**
First - Love the notification Script - thanks for putting this together!

I added the following. 
- Notifications on sprinkler Program Start and Stop
- Refactored run loop, placing all checks in objects - simplify code, minimize if checks in run loop
- Various tweaks (sound for Pushover) and debug messages added.

Feel free to merge if the main branch if you want. I've been running these changes for a couple weeks and they have been stable for me. 

-Kirk

### CODE REVIEW

**Comment by poblabs** [comment]
I think this all looks good! I haven't played much with classes, so this is a good learning experience too. I'll merge it in, but I saw 1 thing, should POLL_SLEEP be in the config.yaml?

**Comment by gigapod** [comment]
Cool - glad the mods made sense. 

Python object support isn't too bad and it fit here to refactor the status checks to the given structure. Now in a pure OO design, the status check logic could of been a method on each object, but not needed here since only one sprinkler Pi is being checked. 

I moved the sleep value to a global to see how the delay value impacted performance (not much, which was expected) and as an old habit. You could move it to the config file, but I saw it as more of a developer setting, and not something to expose to the end user. It wouldn't hurt anything to expose it though if you want. 

-Kirk

**Comment by poblabs** [comment]
I hear you, keeping things like that in the main script is an old habit for me too. The config file is a new approach for me to try and make things easier for general release. I'll keep it as-is for now! Thanks again!

**Comment by gigapod** [comment]
Sounds great - happy to help the community. 

Cheers,
-Kirk

**Pull request merged**
